/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.DTController;
import controller.EquipoController;
import controller.JugadorController;
import java.awt.HeadlessException;

import java.util.Calendar;
import java.util.Date;

import javax.swing.JOptionPane;
import model.DT;
import model.Equipo;
import model.Jugador;

/**
 *
 * @author dzark
 */
public class CreateView extends javax.swing.JFrame {

    private Integer idDT;
    private Integer idTeam;
        
    /**
     * Creates new form CreateView
     */
    public CreateView() {
        initComponents();
        this.setLocationRelativeTo(null);  //para centrar la ventana
        
        /* Establecer número random de identificación para DT*/
        randomIdDT();
            
        /* Establecer número de identificación para equipo*/
        randomIdEquipo();
        
        /* Establecer número de identificación para jugador*/
        randomIdJugador();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CreateTabEquipo = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        idCreateDT = new javax.swing.JTextField();
        nameCreateDT = new javax.swing.JTextField();
        lastnameCreateDT = new javax.swing.JTextField();
        birthdateCreateDT = new com.toedter.calendar.JDateChooser();
        monthCreateDT = new com.toedter.calendar.JMonthChooser();
        yearCreateDT = new com.toedter.calendar.JYearChooser();
        buttonCreateDT = new javax.swing.JButton();
        cleanCreateDT = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        idCreateEquipo = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        nameCreateEquipo = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        cityCreateEquipo = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        StadiumnameCreateEquipo = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        yearCreateEquipo = new com.toedter.calendar.JYearChooser();
        backCreateEquipo = new javax.swing.JButton();
        cleanCreateEquipo = new javax.swing.JButton();
        buttonCreateEquipo = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        DTnameCreateEquipo = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        idCreateJugador = new javax.swing.JTextField();
        nameCreateJugador = new javax.swing.JTextField();
        lastnameCreateJugador = new javax.swing.JTextField();
        birthdateCreateJugador = new com.toedter.calendar.JDateChooser();
        jLabel11 = new javax.swing.JLabel();
        positionCreateJugador = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        TeamnameCreateJugador = new javax.swing.JTextField();
        cleanCreateJugador = new javax.swing.JButton();
        backCreateJugador = new javax.swing.JButton();
        buttonCreateJugador = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        CreateTabEquipo.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Crear", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.BOTTOM, new java.awt.Font("Fira Mono", 1, 16))); // NOI18N
        CreateTabEquipo.setToolTipText("");
        CreateTabEquipo.setFont(new java.awt.Font("Fira Mono Medium", 0, 16)); // NOI18N

        jLabel1.setText("Identificación");

        jLabel2.setText("Nombres");

        jLabel3.setText("Apellidos");

        jLabel4.setText("Fecha de nacimiento");

        jLabel5.setText("Mes de contratación");

        jLabel6.setText("Año de contratación");

        idCreateDT.setEditable(false);
        idCreateDT.setToolTipText("Identificación por defecto");
        idCreateDT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idCreateDTActionPerformed(evt);
            }
        });

        lastnameCreateDT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastnameCreateDTActionPerformed(evt);
            }
        });

        buttonCreateDT.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        buttonCreateDT.setText("Crear");
        buttonCreateDT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCreateDTActionPerformed(evt);
            }
        });

        cleanCreateDT.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        cleanCreateDT.setText("Limpiar");
        cleanCreateDT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cleanCreateDTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel6)
                        .addComponent(jLabel5)))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(yearCreateDT, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(idCreateDT)
                        .addComponent(nameCreateDT, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                        .addComponent(lastnameCreateDT, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(monthCreateDT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(birthdateCreateDT, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(buttonCreateDT, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(cleanCreateDT)
                        .addGap(61, 61, 61))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cleanCreateDT)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(idCreateDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(nameCreateDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lastnameCreateDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(birthdateCreateDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(monthCreateDT, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jLabel5)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(yearCreateDT, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(34, 34, 34))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buttonCreateDT)
                        .addContainerGap())))
        );

        CreateTabEquipo.addTab("Director Técnico", jPanel1);

        jLabel13.setText("Código del equipo");

        idCreateEquipo.setEditable(false);
        idCreateEquipo.setToolTipText("Código por defecto");
        idCreateEquipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idCreateEquipoActionPerformed(evt);
            }
        });

        jLabel14.setText("Nombre");

        nameCreateEquipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameCreateEquipoActionPerformed(evt);
            }
        });

        jLabel15.setText("Ciudad");

        cityCreateEquipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cityCreateEquipoActionPerformed(evt);
            }
        });

        jLabel16.setText("Nombre de estadio");

        StadiumnameCreateEquipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StadiumnameCreateEquipoActionPerformed(evt);
            }
        });

        jLabel17.setText("Año de fundación");

        backCreateEquipo.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        backCreateEquipo.setText("Volver");
        backCreateEquipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backCreateEquipoActionPerformed(evt);
            }
        });

        cleanCreateEquipo.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        cleanCreateEquipo.setText("Limpiar");
        cleanCreateEquipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cleanCreateEquipoActionPerformed(evt);
            }
        });

        buttonCreateEquipo.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        buttonCreateEquipo.setText("Crear");
        buttonCreateEquipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCreateEquipoActionPerformed(evt);
            }
        });

        jLabel18.setText("Id Director Técnico");

        DTnameCreateEquipo.setEditable(false);
        DTnameCreateEquipo.setToolTipText("Id ya ingresado en el paso anterior");
        DTnameCreateEquipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DTnameCreateEquipoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 51, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15))
                        .addGap(61, 61, 61)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(nameCreateEquipo)
                            .addComponent(idCreateEquipo)
                            .addComponent(cityCreateEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addComponent(jLabel17)
                            .addComponent(jLabel18))
                        .addGap(54, 54, 54)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(DTnameCreateEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(yearCreateEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(StadiumnameCreateEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(80, 80, 80)
                .addComponent(cleanCreateEquipo)
                .addGap(64, 64, 64))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(backCreateEquipo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonCreateEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cleanCreateEquipo)
                        .addGap(110, 110, 110))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel13)
                            .addComponent(idCreateEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(nameCreateEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(cityCreateEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(yearCreateEquipo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(StadiumnameCreateEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(DTnameCreateEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backCreateEquipo)
                    .addComponent(buttonCreateEquipo))
                .addContainerGap())
        );

        CreateTabEquipo.addTab("Equipo", jPanel2);

        jLabel7.setText("Fecha de nacimiento");

        jLabel8.setText("Apellidos");

        jLabel9.setText("Nombres");

        jLabel10.setText("Identificación");

        idCreateJugador.setEditable(false);
        idCreateJugador.setToolTipText("Identificación por defecto");
        idCreateJugador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idCreateJugadorActionPerformed(evt);
            }
        });

        lastnameCreateJugador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastnameCreateJugadorActionPerformed(evt);
            }
        });

        jLabel11.setText("Posición");

        positionCreateJugador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                positionCreateJugadorActionPerformed(evt);
            }
        });

        jLabel12.setText("Código del equipo");

        TeamnameCreateJugador.setEditable(false);
        TeamnameCreateJugador.setToolTipText("Código ya ingresado en el paso anterior");
        TeamnameCreateJugador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TeamnameCreateJugadorActionPerformed(evt);
            }
        });

        cleanCreateJugador.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        cleanCreateJugador.setText("Limpiar");
        cleanCreateJugador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cleanCreateJugadorActionPerformed(evt);
            }
        });

        backCreateJugador.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        backCreateJugador.setText("Volver");
        backCreateJugador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backCreateJugadorActionPerformed(evt);
            }
        });

        buttonCreateJugador.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        buttonCreateJugador.setText("Crear");
        buttonCreateJugador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCreateJugadorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel9)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12))
                .addGap(33, 33, 33)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TeamnameCreateJugador)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(positionCreateJugador, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(idCreateJugador)
                        .addComponent(nameCreateJugador, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                        .addComponent(lastnameCreateJugador, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(birthdateCreateJugador, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(66, 66, 66)
                .addComponent(cleanCreateJugador)
                .addGap(61, 61, 61))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(backCreateJugador)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonCreateJugador, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(idCreateJugador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9)
                    .addComponent(nameCreateJugador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lastnameCreateJugador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(25, 25, 25)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(birthdateCreateJugador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(cleanCreateJugador))
                .addGap(29, 29, 29)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(positionCreateJugador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(TeamnameCreateJugador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backCreateJugador)
                    .addComponent(buttonCreateJugador))
                .addContainerGap())
        );

        CreateTabEquipo.addTab("Jugador", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CreateTabEquipo)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CreateTabEquipo)
                .addContainerGap())
        );

        CreateTabEquipo.getAccessibleContext().setAccessibleName("Equipo");

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * Método para establecer número al azar de identificación para DT según rango de números despues del 1234560
     **/
    private void randomIdDT(){
        
        int a = (int)(Math.random()*(123510-123460+1)+123460);  
            String num1 = String.valueOf(a) ;
            idCreateDT.setText( num1 );
    }
    
    /**
     * Método para establecer número de identificación para equipo según rango de números despues del 5
     */
    private void randomIdEquipo(){
        int b = (int)(Math.random()*(55-5+1)+5);  
            String num2 = String.valueOf(b) ;
            idCreateEquipo.setText( num2 );
    }
    
    /**
     * Método para establecer número de identificación para jugador según rango de números despues del 16
     */
    private void randomIdJugador(){
        int c = (int)(Math.random()*(166-16+1)+16);  
            String num3 = String.valueOf(c) ;
            idCreateJugador.setText( num3 );
    }
    
    /**
     * Método para adaptar el tipo de dato de la fecha de la vista al tipo de dato aceptado en BD Sql
     * @param c Entra el tipo de dato recogido por el JCalendar
     * @return Obtiene dato tipo Date Sql con el formato para la BD
     */
    protected static Date fromCalendartoSql(Calendar c){
        /* Se crea instancia de clase Calendar */
        Calendar calendar = Calendar.getInstance();
        calendar.clear();
        /* Asignación de variables a objeto calendario para dar formato*/
        int year = c.get(Calendar.YEAR);
        int month = c.get(Calendar.MONTH );
        int day = c.get(Calendar.DAY_OF_MONTH);
        calendar.set(Calendar.YEAR, year );
        calendar.set(Calendar.MONTH, month);
        calendar.set(Calendar.DAY_OF_MONTH, day);
        java.sql.Date sqlDate = new java.sql.Date(calendar.getTimeInMillis()) ;
        return sqlDate;
    }
    
    private void lastnameCreateDTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastnameCreateDTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lastnameCreateDTActionPerformed

    private void idCreateDTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idCreateDTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idCreateDTActionPerformed

    /**
     * Método para limpiar datos del DT
     * @param evt 
     */
    private void cleanCreateDTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cleanCreateDTActionPerformed
        /* Al limpiar se debe generar un nuevo Id, por si se crea un nuevo DT */
        randomIdDT();
        //idCreateDT.setText("");
        nameCreateDT.setText("");
        lastnameCreateDT.setText("");
    }//GEN-LAST:event_cleanCreateDTActionPerformed

    /**
     * Método para crear un nuevo DT
     * @param evt 
     */
    private void buttonCreateDTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCreateDTActionPerformed
        DTController dtc = new DTController();
        Integer id = null;
        try{
            if(!"".equals(nameCreateDT.getText()) || !"".equals(lastnameCreateDT.getText()) ){
            
                id = Integer.parseInt(idCreateDT.getText()) ;
                String nombre = nameCreateDT.getText();
                String apellido = lastnameCreateDT.getText();
                java.util.Calendar jud =  birthdateCreateDT.getCalendar() ;
                Date sqlDate = fromCalendartoSql(jud);
        
                Integer mesContrato = monthCreateDT.getMonth() + 1 ;
                Integer anioContrato = yearCreateDT.getYear();
                
                DT dt = new DT(id, nombre, apellido, sqlDate, mesContrato, anioContrato);
                dtc.saveDT(dt);
        
                //Para establecer el mismo id del DT en Tab Equipo
                idDT = Integer.parseInt(idCreateDT.getText()) ;
                DTnameCreateEquipo.setText(idDT.toString());
        
                JOptionPane.showMessageDialog(null, "El director técnico fue creado con exito \n Ahora puede asignarle un equipo en la siguiente pestaña");
            } else{
                JOptionPane.showMessageDialog(null, "El director técnico no se pudo crear, por favor llene los datos");
            }
        } catch (HeadlessException | NumberFormatException ex){
            JOptionPane.showMessageDialog(null, "El director técnico no se pudo crear, por favor llene los datos");
        }
    }//GEN-LAST:event_buttonCreateDTActionPerformed

    private void idCreateJugadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idCreateJugadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idCreateJugadorActionPerformed

    private void lastnameCreateJugadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastnameCreateJugadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lastnameCreateJugadorActionPerformed

    private void positionCreateJugadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_positionCreateJugadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_positionCreateJugadorActionPerformed

    private void TeamnameCreateJugadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TeamnameCreateJugadorActionPerformed
        
        
    }//GEN-LAST:event_TeamnameCreateJugadorActionPerformed

    /**
     * Método para limpiar datos del jugador
     * @param evt 
     */
    private void cleanCreateJugadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cleanCreateJugadorActionPerformed
        /* Al limpiar se debe generar un nuevo Id, por si se crea un nuevo Jugador */
        randomIdJugador();
        //idCreateJugador.setText("");
        nameCreateJugador.setText("");
        lastnameCreateJugador.setText("");
        positionCreateJugador.setText("");
        
    }//GEN-LAST:event_cleanCreateJugadorActionPerformed

    private void backCreateJugadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backCreateJugadorActionPerformed
        TournamentView tournamentview = new TournamentView();
        tournamentview.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backCreateJugadorActionPerformed

    private void idCreateEquipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idCreateEquipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idCreateEquipoActionPerformed

    private void cityCreateEquipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cityCreateEquipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cityCreateEquipoActionPerformed

    private void StadiumnameCreateEquipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StadiumnameCreateEquipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_StadiumnameCreateEquipoActionPerformed

    private void nameCreateEquipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameCreateEquipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameCreateEquipoActionPerformed

    private void backCreateEquipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backCreateEquipoActionPerformed
        TournamentView tournamentview = new TournamentView();
        tournamentview.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backCreateEquipoActionPerformed

    /**
     * Método para limpiar datos del equipo
     * @param evt 
     */
    private void cleanCreateEquipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cleanCreateEquipoActionPerformed
        /* Al limpiar se debe generar un nuevo Id, por si se crea un nuevo Equipo */
        randomIdEquipo();
        //idCreateEquipo.setText("");
        nameCreateEquipo.setText("");
        cityCreateEquipo.setText("");
        StadiumnameCreateEquipo.setText("");
        
    }//GEN-LAST:event_cleanCreateEquipoActionPerformed

    /**
     * Método para crear un nuevo equipo
     * @param evt 
     */
    private void buttonCreateEquipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCreateEquipoActionPerformed
        EquipoController eqc = new EquipoController();
        try{    
            if(!"".equals( nameCreateEquipo.getText()) || !"".equals( cityCreateEquipo .getText() ) ){
                
                Integer codigo = Integer.parseInt(idCreateEquipo.getText()) ;
                String nombre = nameCreateEquipo.getText();
                String ciudad = cityCreateEquipo.getText();
                String estadio = StadiumnameCreateEquipo.getText();
                Integer anioNum = yearCreateEquipo.getYear() ;
                String anio = anioNum.toString();
                Integer codigoDT = Integer.parseInt(DTnameCreateEquipo.getText());
        
                Equipo eq = new Equipo(codigo, nombre, ciudad, estadio, anio, codigoDT);
                eqc.saveEquipo(eq);
        
                //Para establecer el mismo codigo del Equipo en Tab Jugador
                idTeam = Integer.parseInt(idCreateEquipo.getText()) ;
                TeamnameCreateJugador.setText(idTeam.toString());
        
                JOptionPane.showMessageDialog(null, "El equipo fue creado con exito \n Ahora puede crear jugadores para este equipo en la siguiente pestaña");
            } else{
                JOptionPane.showMessageDialog(null, "No se pudo crear el equipo, por favor llene los datos");
            }
        } catch (HeadlessException | NumberFormatException ex){
            JOptionPane.showMessageDialog(null, "No se pudo crear el equipo, por favor llene los datos");
        }  
    }//GEN-LAST:event_buttonCreateEquipoActionPerformed

    /**
     * Método para crear un nuevo jugador
     * @param evt 
     */
    private void buttonCreateJugadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCreateJugadorActionPerformed
        
        JugadorController jd = new JugadorController();
        
        try{
            if( !"".equals( nameCreateJugador.getText() ) || !"".equals( lastnameCreateJugador.getText() ) ){
                Integer id = Integer.parseInt(idCreateJugador.getText()) ;
                String nombre = nameCreateJugador.getText();
                String apellido = lastnameCreateJugador.getText();
                java.util.Calendar jug =  birthdateCreateJugador.getCalendar() ;
                Date sqlDate = fromCalendartoSql(jug);
        
                //java.sql.Date datejSql= new java.sql.Date(jug.getYear(),jug.getMonth(),jug.getDay()); Método deprecated
                String posicion = positionCreateJugador.getText();
                Integer codigoTeam = Integer.parseInt(TeamnameCreateJugador.getText());
        
                Jugador jg = new Jugador(id, nombre, apellido, sqlDate, posicion, codigoTeam);
                jd.saveJugador(jg);
        
               
                JOptionPane.showMessageDialog(null, "El jugador fue creado con exito");
            } else{
                JOptionPane.showMessageDialog(null, "El jugador no se pudo crear, por favor llene los datos");
            }
        } catch (HeadlessException | NumberFormatException ex){
                JOptionPane.showMessageDialog(null, "El jugador no se pudo crear, por favor llene los datos");
        }
    }//GEN-LAST:event_buttonCreateJugadorActionPerformed

    private void DTnameCreateEquipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DTnameCreateEquipoActionPerformed
        
    }//GEN-LAST:event_DTnameCreateEquipoActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(CreateView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(CreateView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(CreateView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(CreateView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new CreateView().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane CreateTabEquipo;
    private javax.swing.JTextField DTnameCreateEquipo;
    private javax.swing.JTextField StadiumnameCreateEquipo;
    private javax.swing.JTextField TeamnameCreateJugador;
    private javax.swing.JButton backCreateEquipo;
    private javax.swing.JButton backCreateJugador;
    private com.toedter.calendar.JDateChooser birthdateCreateDT;
    private com.toedter.calendar.JDateChooser birthdateCreateJugador;
    private javax.swing.JButton buttonCreateDT;
    private javax.swing.JButton buttonCreateEquipo;
    private javax.swing.JButton buttonCreateJugador;
    private javax.swing.JTextField cityCreateEquipo;
    private javax.swing.JButton cleanCreateDT;
    private javax.swing.JButton cleanCreateEquipo;
    private javax.swing.JButton cleanCreateJugador;
    private javax.swing.JTextField idCreateDT;
    private javax.swing.JTextField idCreateEquipo;
    private javax.swing.JTextField idCreateJugador;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField lastnameCreateDT;
    private javax.swing.JTextField lastnameCreateJugador;
    private com.toedter.calendar.JMonthChooser monthCreateDT;
    private javax.swing.JTextField nameCreateDT;
    private javax.swing.JTextField nameCreateEquipo;
    private javax.swing.JTextField nameCreateJugador;
    private javax.swing.JTextField positionCreateJugador;
    private com.toedter.calendar.JYearChooser yearCreateDT;
    private com.toedter.calendar.JYearChooser yearCreateEquipo;
    // End of variables declaration//GEN-END:variables
}
