/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.DTController;
import static controller.EquipoController.updateCombo;
import controller.JugadorController;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import model.DT;
import model.Jugador;

/**
 *
 * @author dzark
 */
public class ReadView extends javax.swing.JFrame {
    
    private ArrayList<String> equipos;

    /**
     * Creates new form ReadView
     */
    public ReadView() {
        initComponents();
        this.setLocationRelativeTo(null); //para centrar la ventana
        
        /* Inicialización de la ventana con cada equipo de la BD 
        como opción en el combobox */
        equipos = updateCombo();
        equipos.forEach((s) -> {
            ComboBoxView.addItem(s);      
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        backView = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        TableDT = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableJugador = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        ComboBoxView = new javax.swing.JComboBox<>();
        buttonView = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Ver", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.BOTTOM, new java.awt.Font("Fira Mono", 1, 14))); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(645, 438));

        backView.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        backView.setText("Volver");
        backView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backViewActionPerformed(evt);
            }
        });

        TableDT.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nombre", "Apellido", "Fecha de nacimiento", "Mes contrato", "Año contrato"
            }
        ));
        jScrollPane2.setViewportView(TableDT);

        jLabel3.setFont(new java.awt.Font("Fira Mono", 1, 14)); // NOI18N
        jLabel3.setText("Director técnico");

        jLabel2.setFont(new java.awt.Font("Fira Mono", 1, 14)); // NOI18N
        jLabel2.setText("Jugadores");

        TableJugador.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nombre", "Apellido", "Fecha de nacimiento", "Posición"
            }
        ));
        jScrollPane1.setViewportView(TableJugador);

        jLabel1.setText("Seleccione el equipo");

        ComboBoxView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxViewActionPerformed(evt);
            }
        });

        buttonView.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        buttonView.setText("Ver plantilla");
        buttonView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonViewActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(backView)
                .addGap(36, 36, 36))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel3)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 602, Short.MAX_VALUE)
                        .addComponent(jScrollPane2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(ComboBoxView, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(buttonView)
                .addGap(35, 35, 35))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(ComboBoxView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonView))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(backView))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 666, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 442, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backViewActionPerformed
        TournamentView tournamentview = new TournamentView();
        tournamentview.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backViewActionPerformed

                
    private void ComboBoxViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxViewActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboBoxViewActionPerformed

    /**
     * Método para visualizar las tablas de DT y jugadores
     * @param evt 
     */
    private void buttonViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonViewActionPerformed
       
        String selection = ComboBoxView.getSelectedItem().toString();
        
        /**
         * Proceso para borrar y actualizar la lista de jugadores, según selección en combobox
         */
        JugadorController jdc = new JugadorController();
        
        List<Jugador> jugadores = jdc.readJugadores(selection) ;
        
        DefaultTableModel m = (DefaultTableModel) TableJugador.getModel() ;
        
        int totalFilasJ = m.getRowCount();
        
        for(int i = totalFilasJ - 1; i >= 0; i--)        
            m.removeRow(i);
        
        for(Jugador j : jugadores)
        {
            m.addRow(new Object[] {j.getId(), j.getNombre(), j.getApellido(), j.getFechaNacimiento() , j.getPosicion() });
        }
        
        /**
         * Proceso para borrar y actualizar la lista de DT, según selección en combobox
         */
        DTController dtc = new DTController();
        DT DTs = dtc.readDT(selection);
        
        DefaultTableModel mm = (DefaultTableModel) TableDT.getModel();
        
        int totalFilasDT = mm.getRowCount();
        
        for(int i = totalFilasDT - 1; i>= 0; i--)
            mm.removeRow(i);
        
        mm.addRow(new Object[] {DTs.getId(), DTs.getNombre(), DTs.getApellido(), DTs.getFechaNacimiento(), DTs.getMesContrato(), DTs.getAnioContrato() } );
        
    }//GEN-LAST:event_buttonViewActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboBoxView;
    private javax.swing.JTable TableDT;
    private javax.swing.JTable TableJugador;
    private javax.swing.JButton backView;
    private javax.swing.JButton buttonView;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
